-- Adminer 4.1.0 MySQL dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

INSERT INTO `articles` (`id`, `name`, `author_id`, `created_at`, `content`, `hide`) VALUES
(1,	'Relax po práci v hospodě!',	11,	'2014-09-20 13:28:10',	'… hdklfjlgkhjhljdhk;ldfhljdh;fldkjhk;dfljhklghl;djfhdhola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n… hola škola na nás volá, a my jdeme, mámo, táto, ať je zima nebo bláto … (František Hrubín) Po krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost. Organizace prvního týdne probíhá následujícím způsobem: Pondělí: první i druhý stupeň 1 vyučovací hodina Úterý: první stupeň 4 a druhý stupeň 5 třídnických hodin Středa – pátek: dle rozvrhu bez odpoledního vyučování Prvňáci: Pondělí: 1 vyučovací hodiny Úterý: 2 vyučovací hodiny Středa – pátek 4 vyučovací hodiny PROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)… hola škola na nás volá, a my jdeme, mámo, táto, ať je zima nebo bláto … (František Hrubín) Po krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost. Organizace prvního týdne probíhá následujícím způsobem: Pondělí: první i druhý stupeň 1 vyučovací hodina Úterý: první stupeň 4 a druhý stupeň 5 třídnických hodin Středa – pátek: dle rozvrhu bez odpoledního vyučování Prvňáci: Pondělí: 1 vyučovací hodiny Úterý: 2 vyučovací hodiny Středa – pátek 4 vyučovací hodiny PROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)… hola škola na nás volá, a my jdeme, mámo, táto, ať je zima nebo bláto … (František Hrubín) Po krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost. Organizace prvního týdne probíhá následujícím způsobem: Pondělí: první i druhý stupeň 1 vyučovací hodina Úterý: první stupeň 4 a druhý stupeň 5 třídnických hodin Středa – pátek: dle rozvrhu bez odpoledního vyučování Prvňáci: Pondělí: 1 vyučovací hodiny Úterý: 2 vyučovací hodiny Středa – pátek 4 vyučovací hodiny PROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(3,	'Relax po práci v hospodě!',	14,	'2014-09-20 13:28:10',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(42,	'Relax po práci v hospodě!',	14,	'2014-09-20 13:28:10',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(43,	'Relax po práci v hospodě!',	14,	'2014-09-20 13:28:10',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(44,	'Relax po práci v hospodě!',	10,	'2014-09-20 13:28:10',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(45,	'Relax po práci v hospodě!',	10,	'2014-09-20 13:28:10',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(46,	'Relax po práci v hospodě!',	10,	'2014-09-20 13:28:10',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(47,	'Relax po práci v hospodě!',	10,	'2014-09-20 13:28:10',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(48,	'Relax po práci v hospodě!',	10,	'2014-09-20 13:28:10',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(49,	'Relax po práci v hospodě!',	10,	'2014-09-20 13:28:10',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(50,	'Relax po práci v hospodě!',	10,	'2014-09-20 13:28:10',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(56,	'Relax po práci v hospodě!',	10,	'2014-09-20 13:28:10',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(57,	'Relax po práci v hospodě!',	10,	'2014-09-20 13:28:10',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(58,	'Relax po práci v hospodě!',	10,	'2014-09-20 13:28:10',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(59,	'Relax po práci v hospodě!',	10,	'2014-09-20 13:28:10',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(60,	'Relax po práci v hospodě!',	10,	'2014-09-20 13:28:10',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(61,	'Relax po práci v hospodě!',	10,	'2014-09-20 13:28:10',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(63,	'Relax po práci v hospodě!',	10,	'2014-09-20 13:28:10',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(64,	'df',	0,	'2014-09-27 11:01:23',	'sdfs',	0),
(65,	'dfgfgdfsgdsg',	0,	'2014-09-29 21:49:21',	'<ol>\n<li>sgfsddfsgdfsgkhgdclhashlfh</li>\n<li>d.hfjksadhfkljhsak<strong>djhfkjsdahkjfhkalsjdhfkjls</strong></li>\n<li><strong>adhkfjhdskajfhkjsadh</strong>kjfhsdakjfhkjsda<em>hfkjsahfkjlhsadkljfha</em></li>\n</ol>',	0),
(67,	'cxc',	0,	'2014-09-27 11:05:36',	'vc',	0),
(72,	'asfd',	0,	'2014-09-27 11:13:02',	'sdfasdfsad',	0),
(73,	'kkkkkkk',	0,	'2014-09-27 11:31:04',	'llllll',	0),
(74,	'gdhghgh',	0,	'2014-09-27 11:44:40',	'fghdhf',	0),
(75,	'aaa',	0,	'2014-09-27 16:54:45',	'aaa',	0),
(76,	'dsgsdgfsg',	0,	'2014-09-29 21:44:14',	'<p>ffdgsd</p>',	0)
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `name` = VALUES(`name`), `author_id` = VALUES(`author_id`), `created_at` = VALUES(`created_at`), `content` = VALUES(`content`), `hide` = VALUES(`hide`);


INSERT INTO `images` (`id`, `id_record`, `path_preview`, `path_real`) VALUES
(1,	72,	'/data/thumbs/1954269bbecf7443.97062442.png',	'/data/1954269bbecf7443.97062442.png'),
(3,	74,	'/data/thumbs/85426a328077479.09587614.jpg',	'/data/85426a328077479.09587614.jpg'),
(4,	75,	'/data/thumbs/55426ebd5a51df9.74965060.jpg',	'/data/55426ebd5a51df9.74965060.jpg'),
(5,	75,	'/data/thumbs/105426ebd64a6400.88686530.jpg',	'/data/105426ebd64a6400.88686530.jpg'),
(6,	76,	'/data/thumbs/15429d2ae98b492.57843477.jpg',	'/data/15429d2ae98b492.57843477.jpg'),
(7,	76,	'/data/thumbs/15429d2af55df03.96536056.jpg',	'/data/15429d2af55df03.96536056.jpg'),
(8,	76,	'/data/thumbs/35429d2afe8d0b5.93487429.jpg',	'/data/35429d2afe8d0b5.93487429.jpg')
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `id_record` = VALUES(`id_record`), `path_preview` = VALUES(`path_preview`), `path_real` = VALUES(`path_real`);

INSERT INTO `ip_list` (`id`, `ip`, `created_at`) VALUES
(2173,	'localhost',	'2014-09-27 21:36:45'),
(2174,	'localhost',	'2014-09-27 21:39:01'),
(2175,	'localhost',	'2014-09-27 21:39:01'),
(2176,	'localhost',	'2014-09-27 21:39:03'),
(2177,	'localhost',	'2014-09-28 19:28:21'),
(2178,	'localhost',	'2014-09-28 19:28:38'),
(2179,	'localhost',	'2014-09-28 19:28:40'),
(2180,	'localhost',	'2014-09-28 19:28:40'),
(2181,	'localhost',	'2014-09-28 19:28:41'),
(2182,	'localhost',	'2014-09-29 21:34:03'),
(2183,	'localhost',	'2014-09-29 21:34:05'),
(2184,	'localhost',	'2014-09-29 21:34:06'),
(2185,	'localhost',	'2014-09-29 21:34:06'),
(2186,	'localhost',	'2014-09-29 21:34:08'),
(2187,	'localhost',	'2014-09-29 21:39:21'),
(2188,	'localhost',	'2014-09-29 21:44:01'),
(2189,	'localhost',	'2014-09-29 21:44:01'),
(2190,	'localhost',	'2014-09-29 21:44:03'),
(2191,	'localhost',	'2014-09-29 21:44:14'),
(2192,	'localhost',	'2014-09-29 21:44:16'),
(2193,	'localhost',	'2014-09-29 21:44:16'),
(2194,	'localhost',	'2014-09-29 21:45:37'),
(2195,	'localhost',	'2014-09-29 21:47:25'),
(2196,	'localhost',	'2014-09-29 21:49:04'),
(2197,	'localhost',	'2014-09-29 21:49:04'),
(2198,	'localhost',	'2014-09-29 21:49:11'),
(2199,	'localhost',	'2014-09-29 21:49:21'),
(2200,	'localhost',	'2014-09-29 21:49:21'),
(2201,	'localhost',	'2014-09-29 21:49:21'),
(2202,	'localhost',	'2014-09-30 11:56:10')
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `ip` = VALUES(`ip`), `created_at` = VALUES(`created_at`);

INSERT INTO `pages` (`id`, `name`, `author_id`, `created_at`, `content`, `hide`) VALUES
(1,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hdklfjlgkhjhljdhk;ldfhljdh;fldkjhk;dfljhklghl;djfhdhola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n… hola škola na nás volá, a my jdeme, mámo, táto, ať je zima nebo bláto … (František Hrubín) Po krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost. Organizace prvního týdne probíhá následujícím způsobem: Pondělí: první i druhý stupeň 1 vyučovací hodina Úterý: první stupeň 4 a druhý stupeň 5 třídnických hodin Středa – pátek: dle rozvrhu bez odpoledního vyučování Prvňáci: Pondělí: 1 vyučovací hodiny Úterý: 2 vyučovací hodiny Středa – pátek 4 vyučovací hodiny PROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)… hola škola na nás volá, a my jdeme, mámo, táto, ať je zima nebo bláto … (František Hrubín) Po krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost. Organizace prvního týdne probíhá následujícím způsobem: Pondělí: první i druhý stupeň 1 vyučovací hodina Úterý: první stupeň 4 a druhý stupeň 5 třídnických hodin Středa – pátek: dle rozvrhu bez odpoledního vyučování Prvňáci: Pondělí: 1 vyučovací hodiny Úterý: 2 vyučovací hodiny Středa – pátek 4 vyučovací hodiny PROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)… hola škola na nás volá, a my jdeme, mámo, táto, ať je zima nebo bláto … (František Hrubín) Po krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost. Organizace prvního týdne probíhá následujícím způsobem: Pondělí: první i druhý stupeň 1 vyučovací hodina Úterý: první stupeň 4 a druhý stupeň 5 třídnických hodin Středa – pátek: dle rozvrhu bez odpoledního vyučování Prvňáci: Pondělí: 1 vyučovací hodiny Úterý: 2 vyučovací hodiny Středa – pátek 4 vyučovací hodiny PROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(3,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(42,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(43,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(44,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(45,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(46,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(47,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(48,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(49,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(50,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(51,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(52,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hdklfjlgkhjhljdhk;ldfhljdh;fldkjhk;dfljhklghl;djfhdhola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n… hola škola na nás volá, a my jdeme, mámo, táto, ať je zima nebo bláto … (František Hrubín) Po krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost. Organizace prvního týdne probíhá následujícím způsobem: Pondělí: první i druhý stupeň 1 vyučovací hodina Úterý: první stupeň 4 a druhý stupeň 5 třídnických hodin Středa – pátek: dle rozvrhu bez odpoledního vyučování Prvňáci: Pondělí: 1 vyučovací hodiny Úterý: 2 vyučovací hodiny Středa – pátek 4 vyučovací hodiny PROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)… hola škola na nás volá, a my jdeme, mámo, táto, ať je zima nebo bláto … (František Hrubín) Po krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost. Organizace prvního týdne probíhá následujícím způsobem: Pondělí: první i druhý stupeň 1 vyučovací hodina Úterý: první stupeň 4 a druhý stupeň 5 třídnických hodin Středa – pátek: dle rozvrhu bez odpoledního vyučování Prvňáci: Pondělí: 1 vyučovací hodiny Úterý: 2 vyučovací hodiny Středa – pátek 4 vyučovací hodiny PROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)… hola škola na nás volá, a my jdeme, mámo, táto, ať je zima nebo bláto … (František Hrubín) Po krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost. Organizace prvního týdne probíhá následujícím způsobem: Pondělí: první i druhý stupeň 1 vyučovací hodina Úterý: první stupeň 4 a druhý stupeň 5 třídnických hodin Středa – pátek: dle rozvrhu bez odpoledního vyučování Prvňáci: Pondělí: 1 vyučovací hodiny Úterý: 2 vyučovací hodiny Středa – pátek 4 vyučovací hodiny PROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(53,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(54,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(55,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(56,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(57,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(58,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(59,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(60,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(61,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(62,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(63,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0)
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `name` = VALUES(`name`), `author_id` = VALUES(`author_id`), `created_at` = VALUES(`created_at`), `content` = VALUES(`content`), `hide` = VALUES(`hide`);

INSERT INTO `users` (`id`, `username`, `realname`, `email`, `password`, `role`, `author_id`) VALUES
(10,	'admin',	'admin',	'admin',	'$2y$10$fqrqQmCxAc0eBSNBeGHQIOBHICgC9PP4SXILXf5Mvwrpa7nkqSRBe',	'admin',	10),
(12,	'red',	'red',	'ma',	'$2y$10$fqrqQmCxAc0eBSNBeGHQIOBHICgC9PP4SXILXf5Mvwrpa7nkqSRBe',	'admin',	0),
(13,	'a',	'a',	'a',	'$2y$10$xj5Bx3tka3qWHcV3z0d4jOzYodeKYBnW82YPXiAiF4i1bxyWVj1oa',	'editor',	0),
(14,	'p',	'p',	'p',	'$2y$10$p8SJYX9gB8Ku6TsDYGh98OcoWM36Oi7WwFiLkeYS3eWhbcYZSK69K',	'publisher',	0)
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `username` = VALUES(`username`), `realname` = VALUES(`realname`), `email` = VALUES(`email`), `password` = VALUES(`password`), `role` = VALUES(`role`), `author_id` = VALUES(`author_id`);

-- 2014-09-30 20:12:26
