-- Adminer 4.1.0 MySQL dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `articles`;
CREATE TABLE `articles` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `author_id` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `content` text NOT NULL,
  `hide` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `articles` (`id`, `name`, `author_id`, `created_at`, `content`, `hide`) VALUES
(1,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hdklfjlgkhjhljdhk;ldfhljdh;fldkjhk;dfljhklghl;djfhdhola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n… hola škola na nás volá, a my jdeme, mámo, táto, ať je zima nebo bláto … (František Hrubín) Po krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost. Organizace prvního týdne probíhá následujícím způsobem: Pondělí: první i druhý stupeň 1 vyučovací hodina Úterý: první stupeň 4 a druhý stupeň 5 třídnických hodin Středa – pátek: dle rozvrhu bez odpoledního vyučování Prvňáci: Pondělí: 1 vyučovací hodiny Úterý: 2 vyučovací hodiny Středa – pátek 4 vyučovací hodiny PROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)… hola škola na nás volá, a my jdeme, mámo, táto, ať je zima nebo bláto … (František Hrubín) Po krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost. Organizace prvního týdne probíhá následujícím způsobem: Pondělí: první i druhý stupeň 1 vyučovací hodina Úterý: první stupeň 4 a druhý stupeň 5 třídnických hodin Středa – pátek: dle rozvrhu bez odpoledního vyučování Prvňáci: Pondělí: 1 vyučovací hodiny Úterý: 2 vyučovací hodiny Středa – pátek 4 vyučovací hodiny PROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)… hola škola na nás volá, a my jdeme, mámo, táto, ať je zima nebo bláto … (František Hrubín) Po krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost. Organizace prvního týdne probíhá následujícím způsobem: Pondělí: první i druhý stupeň 1 vyučovací hodina Úterý: první stupeň 4 a druhý stupeň 5 třídnických hodin Středa – pátek: dle rozvrhu bez odpoledního vyučování Prvňáci: Pondělí: 1 vyučovací hodiny Úterý: 2 vyučovací hodiny Středa – pátek 4 vyučovací hodiny PROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(3,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(42,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(43,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(44,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(45,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(46,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(47,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(48,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(49,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(50,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(51,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(52,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hdklfjlgkhjhljdhk;ldfhljdh;fldkjhk;dfljhklghl;djfhdhola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n… hola škola na nás volá, a my jdeme, mámo, táto, ať je zima nebo bláto … (František Hrubín) Po krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost. Organizace prvního týdne probíhá následujícím způsobem: Pondělí: první i druhý stupeň 1 vyučovací hodina Úterý: první stupeň 4 a druhý stupeň 5 třídnických hodin Středa – pátek: dle rozvrhu bez odpoledního vyučování Prvňáci: Pondělí: 1 vyučovací hodiny Úterý: 2 vyučovací hodiny Středa – pátek 4 vyučovací hodiny PROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)… hola škola na nás volá, a my jdeme, mámo, táto, ať je zima nebo bláto … (František Hrubín) Po krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost. Organizace prvního týdne probíhá následujícím způsobem: Pondělí: první i druhý stupeň 1 vyučovací hodina Úterý: první stupeň 4 a druhý stupeň 5 třídnických hodin Středa – pátek: dle rozvrhu bez odpoledního vyučování Prvňáci: Pondělí: 1 vyučovací hodiny Úterý: 2 vyučovací hodiny Středa – pátek 4 vyučovací hodiny PROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)… hola škola na nás volá, a my jdeme, mámo, táto, ať je zima nebo bláto … (František Hrubín) Po krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost. Organizace prvního týdne probíhá následujícím způsobem: Pondělí: první i druhý stupeň 1 vyučovací hodina Úterý: první stupeň 4 a druhý stupeň 5 třídnických hodin Středa – pátek: dle rozvrhu bez odpoledního vyučování Prvňáci: Pondělí: 1 vyučovací hodiny Úterý: 2 vyučovací hodiny Středa – pátek 4 vyučovací hodiny PROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(53,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(54,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(55,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(56,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(57,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(58,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(59,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(60,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(61,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(62,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(63,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0)
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `name` = VALUES(`name`), `author_id` = VALUES(`author_id`), `created_at` = VALUES(`created_at`), `content` = VALUES(`content`), `hide` = VALUES(`hide`);

DROP TABLE IF EXISTS `ip_list`;
CREATE TABLE `ip_list` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ip` text NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `ip_list` (`id`, `ip`, `created_at`) VALUES
(212,	'localhost',	'2014-09-13 19:59:01'),
(213,	'localhost',	'2014-09-13 20:00:40'),
(214,	'localhost',	'2014-09-13 20:00:47'),
(215,	'localhost',	'2014-09-13 20:01:02'),
(216,	'localhost',	'2014-09-13 20:01:03'),
(217,	'localhost',	'2014-09-13 20:01:21'),
(218,	'localhost',	'2014-09-13 20:01:22'),
(219,	'localhost',	'2014-09-13 20:01:22'),
(220,	'localhost',	'2014-09-13 20:01:28'),
(221,	'localhost',	'2014-09-13 20:01:30'),
(222,	'localhost',	'2014-09-13 20:01:31'),
(223,	'localhost',	'2014-09-13 20:01:36'),
(224,	'localhost',	'2014-09-13 20:01:37'),
(225,	'localhost',	'2014-09-13 20:01:37'),
(226,	'localhost',	'2014-09-13 20:01:38'),
(227,	'localhost',	'2014-09-13 20:01:39'),
(228,	'localhost',	'2014-09-13 20:01:39'),
(229,	'localhost',	'2014-09-13 20:01:40'),
(230,	'localhost',	'2014-09-13 20:01:41'),
(231,	'localhost',	'2014-09-13 20:01:42'),
(232,	'localhost',	'2014-09-13 20:01:43'),
(233,	'localhost',	'2014-09-13 20:01:44'),
(234,	'localhost',	'2014-09-13 21:50:49'),
(235,	'localhost',	'2014-09-13 21:50:50'),
(236,	'localhost',	'2014-09-13 21:50:53'),
(237,	'localhost',	'2014-09-13 21:50:53'),
(238,	'localhost',	'2014-09-13 21:50:53'),
(239,	'localhost',	'2014-09-13 21:50:57'),
(240,	'localhost',	'2014-09-14 07:38:23'),
(241,	'localhost',	'2014-09-14 07:38:27')
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `ip` = VALUES(`ip`), `created_at` = VALUES(`created_at`);

DROP TABLE IF EXISTS `pages`;
CREATE TABLE `pages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `author_id` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `content` text NOT NULL,
  `hide` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `pages` (`id`, `name`, `author_id`, `created_at`, `content`, `hide`) VALUES
(1,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hdklfjlgkhjhljdhk;ldfhljdh;fldkjhk;dfljhklghl;djfhdhola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n… hola škola na nás volá, a my jdeme, mámo, táto, ať je zima nebo bláto … (František Hrubín) Po krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost. Organizace prvního týdne probíhá následujícím způsobem: Pondělí: první i druhý stupeň 1 vyučovací hodina Úterý: první stupeň 4 a druhý stupeň 5 třídnických hodin Středa – pátek: dle rozvrhu bez odpoledního vyučování Prvňáci: Pondělí: 1 vyučovací hodiny Úterý: 2 vyučovací hodiny Středa – pátek 4 vyučovací hodiny PROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)… hola škola na nás volá, a my jdeme, mámo, táto, ať je zima nebo bláto … (František Hrubín) Po krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost. Organizace prvního týdne probíhá následujícím způsobem: Pondělí: první i druhý stupeň 1 vyučovací hodina Úterý: první stupeň 4 a druhý stupeň 5 třídnických hodin Středa – pátek: dle rozvrhu bez odpoledního vyučování Prvňáci: Pondělí: 1 vyučovací hodiny Úterý: 2 vyučovací hodiny Středa – pátek 4 vyučovací hodiny PROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)… hola škola na nás volá, a my jdeme, mámo, táto, ať je zima nebo bláto … (František Hrubín) Po krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost. Organizace prvního týdne probíhá následujícím způsobem: Pondělí: první i druhý stupeň 1 vyučovací hodina Úterý: první stupeň 4 a druhý stupeň 5 třídnických hodin Středa – pátek: dle rozvrhu bez odpoledního vyučování Prvňáci: Pondělí: 1 vyučovací hodiny Úterý: 2 vyučovací hodiny Středa – pátek 4 vyučovací hodiny PROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(3,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(42,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(43,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(44,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(45,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(46,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(47,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(48,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(49,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(50,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(51,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(52,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hdklfjlgkhjhljdhk;ldfhljdh;fldkjhk;dfljhklghl;djfhdhola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n… hola škola na nás volá, a my jdeme, mámo, táto, ať je zima nebo bláto … (František Hrubín) Po krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost. Organizace prvního týdne probíhá následujícím způsobem: Pondělí: první i druhý stupeň 1 vyučovací hodina Úterý: první stupeň 4 a druhý stupeň 5 třídnických hodin Středa – pátek: dle rozvrhu bez odpoledního vyučování Prvňáci: Pondělí: 1 vyučovací hodiny Úterý: 2 vyučovací hodiny Středa – pátek 4 vyučovací hodiny PROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)… hola škola na nás volá, a my jdeme, mámo, táto, ať je zima nebo bláto … (František Hrubín) Po krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost. Organizace prvního týdne probíhá následujícím způsobem: Pondělí: první i druhý stupeň 1 vyučovací hodina Úterý: první stupeň 4 a druhý stupeň 5 třídnických hodin Středa – pátek: dle rozvrhu bez odpoledního vyučování Prvňáci: Pondělí: 1 vyučovací hodiny Úterý: 2 vyučovací hodiny Středa – pátek 4 vyučovací hodiny PROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)… hola škola na nás volá, a my jdeme, mámo, táto, ať je zima nebo bláto … (František Hrubín) Po krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost. Organizace prvního týdne probíhá následujícím způsobem: Pondělí: první i druhý stupeň 1 vyučovací hodina Úterý: první stupeň 4 a druhý stupeň 5 třídnických hodin Středa – pátek: dle rozvrhu bez odpoledního vyučování Prvňáci: Pondělí: 1 vyučovací hodiny Úterý: 2 vyučovací hodiny Středa – pátek 4 vyučovací hodiny PROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(53,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(54,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(55,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(56,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(57,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(58,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(59,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(60,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(61,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(62,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0),
(63,	'Ahoj',	10,	'2014-09-11 13:13:12',	'… hola škola na nás volá,\r\na my jdeme, mámo, táto,\r\nať je zima nebo bláto … (František Hrubín)\r\n\r\nPo krásných prázdninách se děti vrací zpět do školy, aby dalších deset měsíců opět získávaly vědomosti, poznatky a učily se pro svoji budoucnost.\r\n\r\nOrganizace prvního týdne probíhá následujícím způsobem:\r\nPondělí: první i druhý stupeň 1 vyučovací hodina\r\nÚterý: první stupeň 4 a druhý stupeň 5 třídnických hodin\r\nStředa – pátek: dle rozvrhu bez odpoledního vyučování\r\n\r\nPrvňáci:\r\nPondělí: 1 vyučovací hodiny\r\nÚterý: 2 vyučovací hodiny\r\nStředa – pátek 4 vyučovací hodiny\r\n\r\nPROVOZ ŠKOLNÍ DRUŽINY BĚŽÍ DLE BĚŽNÉHO ŘÁDU ŠD, (6.30 – 17.00)',	0)
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `name` = VALUES(`name`), `author_id` = VALUES(`author_id`), `created_at` = VALUES(`created_at`), `content` = VALUES(`content`), `hide` = VALUES(`hide`);

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL,
  `realname` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `role` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `users` (`id`, `username`, `realname`, `email`, `password`, `role`) VALUES
(10,	'admin',	'admin',	'admin',	'$2y$10$fqrqQmCxAc0eBSNBeGHQIOBHICgC9PP4SXILXf5Mvwrpa7nkqSRBe',	'admin'),
(12,	'red',	'red',	'ma',	'$2y$10$fqrqQmCxAc0eBSNBeGHQIOBHICgC9PP4SXILXf5Mvwrpa7nkqSRBe',	'admin')
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `username` = VALUES(`username`), `realname` = VALUES(`realname`), `email` = VALUES(`email`), `password` = VALUES(`password`), `role` = VALUES(`role`);

-- 2014-09-16 21:54:54
